name: Build in debug configuration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    
    - name: Install dependencies
      run: dotnet restore
    - name: Build builder binary
      run: dotnet publish --configuration Debug --no-restore ReaperKing.Builder -o artifacts\
    - name: Build Reaper King library
      run: dotnet publish --configuration Debug --no-restore ReaperKing.StaticConfig -o artifacts\

    - uses: actions/upload-artifact@v2
      with:
        name: PRK-debug
        path: artifacts/
        if-no-files-found: error
