name: Build in debug configuration

on:
    push:
#        branches: [ master ]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Setup .NET
              uses: actions/setup-dotnet@v1
              with:
                  dotnet-version: 5.0.101

            - name: Install dependencies
              run: dotnet restore
              
            # RK
            
            - name: Build core library
              run: dotnet publish --no-restore
                                  --configuration Debug --output builddir/rk/bin
                                  /p:SatelliteResourceLanguages=en
                                  Xeno.Core
            - name: Build command line tools
              run: dotnet publish --no-restore
                                  --configuration Debug --output builddir/rk/bin
                                  /p:SatelliteResourceLanguages=en
                                  Xeno.CLI
              
            - name: Build common plugins
              run: dotnet publish --no-restore
                                  --configuration Debug --output builddir/rk/bin
                                  /p:SatelliteResourceLanguages=en
                                  Xeno.Plugins
            - name: Build ImageOptimization plugin
              run: dotnet publish --no-restore
                                  --configuration Debug --output builddir/rk/bin
                                  /p:SatelliteResourceLanguages=en
                                  Xeno.Plugins.ImageOptimization
              
            - name: Build common template library
              run: dotnet publish --no-restore
                                  --configuration Debug --output builddir/rk/bin
                                  /p:SatelliteResourceLanguages=en
                                  Xeno.CommonTemplates
            - name: Build Anhydrate template library
              run: dotnet publish --no-restore
                                  --configuration Debug --output builddir/rk/bin
                                  /p:SatelliteResourceLanguages=en
                                  Xeno.Anhydrate
              
            - name: Copy GPLv3 license
              run: cp LICENSE builddir/rk/bin
            - name: Split PDBs into a separate artifact
              run: mkdir builddir/rk/pdb && mv builddir/rk/bin/*.pdb builddir/rk/pdb

            - uses: actions/upload-artifact@v2
              with:
                  name: xeno-cli-debug-bins
                  path: builddir/rk/bin
                  if-no-files-found: error
            - uses: actions/upload-artifact@v2
              with:
                  name: xeno-cli-debug-pdbs
                  path: builddir/rk/pdb
                  if-no-files-found: error

            # POGLIN

            - name: Build Poglin bake library
              run: dotnet publish --no-restore
                                  --configuration Debug --output builddir/poglin/bin
                                  /p:SatelliteResourceLanguages=en
                                  Poglin.StaticConfiguration

            - name: Copy AGPLv3 license
              run: cp LICENSE.POGLIN builddir/poglin/bin
            - name: Remove duplicated files from Rk in Poglin build
              run: cd builddir/rk/bin ;
                   find . -type f -exec rm -rf ../../poglin/bin/{} \; ;
                   cd ../pdb ;
                   find . -type f -exec rm -rf ../../poglin/bin/{} \; ;
                   cd ../..
            - name: Split PDBs into a separate artifact
              run: mkdir builddir/poglin/pdb && mv builddir/poglin/bin/*.pdb builddir/poglin/pdb

            - uses: actions/upload-artifact@v2
              with:
                  name: poglin-agpl-debug-bin
                  path: builddir/poglin/bin
                  if-no-files-found: error
            - uses: actions/upload-artifact@v2
              with:
                  name: poglin-agpl-debug-pdbs
                  path: builddir/poglin/pdb
                  if-no-files-found: error