name: Build in debug configuration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    
    - name: Install dependencies
      run: dotnet restore
    - name: Build builder binary
      run: dotnet build --configuration Debug --no-restore SiteBuilder
    - name: Build Reaper King library
      run: dotnet build --configuration Debug --no-restore ProjectReaperKing
      
    - name: Copy build artifacts
      shell: bash
      run: |
          COR_PATH=SiteBuilder/bin/Debug/netcoreapp3.1
          PRK_PATH=ProjectReaperKing/bin/Debug/netcoreapp3.1
          mkdir -p artifacts/Core artifacts/RK
          mv "$COR_PATH/*.dll" artifacts/Core/
          mv "$COR_PATH/*.pdb" artifacts/Core/
          mv "$COR_PATH/{cs,de,es,fr,it,pl}" artifacts/Core/
          mv "$COR_PATH/{refs,runtimes}" artifacts/Core/
          mv "$PRK_PATH/ProjectReaperKing.{dll,pdb}" artifacts/RK/

    - uses: actions/upload-artifact@v2
      with:
        name: CoreDebugWithPdb
        path: artifacts/Core/
        if-no-files-found: error
      
    - uses: actions/upload-artifact@v2
      with:
        name: RKDebugWithPdb
        path: artifacts/RK/
        if-no-files-found: error
      
